import json
from playwright.sync_api import sync_playwright


def run(playwright):
    browser = playwright.chromium.launch(headless=False)
    context = browser.new_context()
    page = context.new_page()

    # Track failed requests for Use Case 1
    failed_image_urls = []
    page.on(
        "requestfailed",
        lambda request: failed_image_urls.append(request.url)
        if any(ext in request.url.lower() for ext in [".png", ".jpg", ".jpeg", ".svg"])
        else None,
    )

    # ------------------------------------------------------------------
    # USE CASE 1: Abort/Block Requests (Images)
    # ------------------------------------------------------------------
    def image_blocker_handler(route):
        route.abort("blockedbyclient")

    page.route("**/*.{png,jpg,jpeg,svg}", image_blocker_handler)

    # ------------------------------------------------------------------
    # USE CASE 3: Intercept, Inspect, and Modify a Real Response (Orders)
    # ------------------------------------------------------------------
    def modify_order_response(route):
        # Fetch the real order confirmation response from the server
        response = route.fetch()
        try:
            json_body = response.json()
            if "orders" in json_body:
                # Intercept and inject our custom Mock ID before the UI sees it
                json_body["orders"] = ["MOCK_ORDER_999"]
                json_body["message"] = "Intercepted and modified!"
            route.fulfill(response=response, json=json_body)
        except Exception:
            route.continue_()

    page.route("**/api/ecom/order/create-order", modify_order_response)

    # ------------------------------------------------------------------
    # TEST EXECUTION FLOW
    # ------------------------------------------------------------------

    # 1. Navigate to the login page
    page.goto("https://rahulshettyacademy.com/client/")
    page.wait_for_load_state("domcontentloaded")

    # 2. Log in using REAL credentials (removes the authentication freeze)
    print(f"--- Demonstration 2: Capturing Real Authentication ---")
    page.get_by_placeholder("email@example.com").fill("v.d@gmail.com")
    page.get_by_placeholder("enter your passsword").fill("RahulShetty@2026")

    # Capture the genuine network token generated by the server
    with page.expect_response("**/api/ecom/auth/login") as response_info:
        page.get_by_role("button", name="Login").click()

    real_login_response = response_info.value
    captured_token = real_login_response.json().get("token", "NOT_FOUND")
    print(f"Real Token generated by server: {captured_token[:25]}...")
    print("✅ Verified: Successfully logged in without UI freezes.")

    # 3. Inspect and clear the image blocker rule so the dashboard catalog displays
    print(f"\n--- Demonstration 1: Image Blocking Check ---")
    print(f"Blocked Image Requests Count: {len(failed_image_urls)}")

    page.unroute("**/*.{png,jpg,jpeg,svg}", image_blocker_handler)
    print("🔄 Info: Lifted image blocking rules to guarantee UI rendering.")

    # 4. Execute Checkout & Modify Response
    print(f"\n--- Demonstration 3: Response Modification (Orders) ---")

    # Wait for the authentic user catalog items to arrive
    page.locator(".card-body").first.wait_for(state="visible", timeout=15000)
    page.get_by_role("button", name=" Add To Cart").first.click()

    # Navigate to Cart -> Checkout
    page.get_by_role("button", name="Cart").click()
    page.get_by_role("button", name="Checkout").click()

    # Handle the country autocomplete selection securely
    page.get_by_placeholder("Select Country").press_sequentially("ind", delay=100)
    page.get_by_role("button", name=" India").click()

    # Catch the create-order API call during final click
    with page.expect_response("**/api/ecom/order/create-order") as order_response_info:
        page.locator(".action__submit").click()

    modified_order_json = order_response_info.value.json()
    print(f"Server Response modified to payload item: {modified_order_json['orders']}")

    # Confirm the UI printed our injected fake value
    ui_confirmation_text = page.locator("label.ng-star-inserted").text_content()
    print(f"UI Displayed Order ID: {ui_confirmation_text}")

    assert "MOCK_ORDER_999" in ui_confirmation_text, "UI did not show the modified Order ID!"
    print("✅ Verified: The backend response was altered, forcing the UI to display 'MOCK_ORDER_999'.")

    page.wait_for_timeout(2000)
    browser.close()


with sync_playwright() as playwright:
    run(playwright)